### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by MelGGit** [MelGGit/capstone-project#16]
## Value statement - a requirement, not a solution
As a user 
I need to be able to see where i am and what the current search term is 
so that i can navigate myself.

## Description (Text, Scribble, Wireframe, Design)
![header](https://user-images.githubusercontent.com/60812382/122051591-0e890e00-cde5-11eb-9311-86bda16c3c15.png)

## Acceptance criteria
- [ ]  no header on details page
- [ ] on details page only back arrow
- [ ] decide on whether with or without different background color

## Tasks
- [ ] header component
- [ ] implement header in app

## Size
medium
