### ISSUE TITLE
Podcast List (User Sory)

### ISSUE THREAD

**Issue by MelGGit** [MelGGit/capstone-project#2]
## Value statement - a requirement, not a solution
As a user 
I need to be able to see a list of podcasts about batman
so that i get a nice overview about what is available.

## Description (Text, Scribble, Wireframe, Design)
![excalidraw](https://excalidraw.com/#json=5868518079725568,SaxZ4DR09KUw5cjAXHvBnQ)

## Acceptance criteria
- [ ] implement a fetch for example data (url (https://api.podcastindex.org/api/1.0/search/byterm?q=batman+university&pretty)
- [ ] image and title of a card should be clearly visible

## Tasks
- [ ] create Card component with img and title parameter
- [ ] add Card to App component
- [ ] fetch in App component
- [ ] render as many cards as there are podcasts json resulting from the fetch
- [ ] write test for Card component
- [ ] style Card component
- [ ] style App component

## Size
(small)
