### ISSUE TITLE
Get more Information for a podcast on click (User Story)

### ISSUE THREAD

**Issue by MelGGit** [MelGGit/capstone-project#3]
As a user
I want to get more information to a specific podcast
so that i can determine if it fits my needs.

## Description (Text, Scribble, Wireframe, Design)
![searchResult_page_expand_user_story](https://user-images.githubusercontent.com/60812382/120613615-afc3ac00-c456-11eb-97bc-b403bd1e00fc.png)

## Acceptance criteria
- [x] the podcast Card should expand on Click
- [x] the card should shrink back when clicking on it
- [x] the tags should be the categories delivered by the fetch

## Tasks
- [x] update Card with an onClick event to expand
- [x] update Card to incorporate description categories and author
- [x] set those new addiitons to be hidden by default
- [x] onClick those additions should be visible
- [x] when clicking on the openend Card the card should shrink

## Size
medium
