### ISSUE TITLE
favorite Podcast

### ISSUE THREAD

**Issue by MelGGit** [MelGGit/capstone-project#4]
As a user 
I want to be able to favorite podcasts
so that i know to which to listen to next 

## Description (Text, Scribble, Wireframe, Design)
![thrid_user_story](https://user-images.githubusercontent.com/60812382/120513680-cf15f700-c3cc-11eb-93b8-694ca4aef2e4.png)

## Acceptance criteria
- [ ] the bookmarks should be able to toggle between active and inactive
- [ ] when active the podcast should get listed in the favorites
- [ ] when inactive the podcast should not get listed in favorites
- [ ] the button Search should not be visible on favorites page

## Tasks
- [ ] creating two pages
- [ ] one Page SearchResult which renders the available space podcasts
- [ ] one Page Favorites
- [ ] create Buttons to switch between those stages
- [ ] create bookmark
- [ ] crate logic for bookmark

## Size
medium
