### ISSUE TITLE
burger menu

### ISSUE THREAD

**Issue by MelGGit** [MelGGit/capstone-project#5]
As a user
I want to be able to switch conveniently between pages
so that i can see search and favorites

## Description (Text, Scribble, Wireframe, Design)
![fourth_user_story](https://user-images.githubusercontent.com/60812382/120514596-c40f9680-c3cd-11eb-8fe2-e2dff5566235.png)

## Acceptance criteria
- [ ] burger menu which is clickable
- [ ] should have active and inactive states
- [ ] depending on the page the user is on that page gets disabled in the menu

## Tasks
- [ ] create burger menu
- [ ] create logic

## Size
medium

**Comment by badabam** [comment]
Please update the title of the user story. "burger menu" does not fit anymore.
