### ISSUE TITLE
(User-Story) Main Menu

### ISSUE THREAD

**Issue by MelGGit** [MelGGit/capstone-project#6]
As a user
I want to be able to search for specific podcasts and see the top trending and new ones
so that i can get o know other podcasts on one view.

## Description (Text, Scribble, Wireframe, Design)
![main_page_top_user_story](https://user-images.githubusercontent.com/60812382/120609407-6ec99880-c452-11eb-9b01-55b1229afcd3.png)

## Acceptance criteria
- [ ] burger menu has main page as new route
- [ ] the top podcasts get fetched by api
- [ ] when clicking on a podcast it gets expanded like the others on the search result page
- [ ] when clicking on anything but the expanded podcast it shrinks

## Tasks
- [ ] update burger menu
- [ ] create new component for curatedPodcasts
- [ ] implement logic for router and podcast

## Size
medium
